package constants

const (
	ASSET_TYPE_CHART = iota + 1
	ASSET_TYPE_INSIGHT
	ASSET_TYPE_AUDIENCE
)

const (
	CHARACTERISTIC_GENDER = iota + 1
	CHARACTERISTIC_BIRTH_COUNTRY
	CHARACTERISTIC_AGE_GROUP
	CHARACTERISTIC_SOCIAL_MEDIA_DAILY_HOURS
	CHARACTERISTIC_PURCHASES_LAST_MONTH
)

const (
	AGE_GROUP_UNDER_17 = iota + 1
	AGE_GROUP_17_19
	AGE_GROUP_20_29
	AGE_GROUP_30_39
	AGE_GROUP_40_49
	AGE_GROUP_50_59
	AGE_GROUP_60_69
	AGE_GROUP_70_PLUS
)